// <auto-generated />
using System;
using GameHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260422221715_CrearTablaVideojuegoPlataforma")]
    partial class CrearTablaVideojuegoPlataforma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameHub.Domain.Entities.Desarrollador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FechaFundacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("NombreDesarrollador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("NombreDesarrollador")
                        .IsUnique();

                    b.ToTable("Desarrolladores");
                });

            modelBuilder.Entity("GameHub.Domain.Entities.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("NombreGenero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NombreGenero")
                        .IsUnique();

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("GameHub.Domain.Entities.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly>("FechaLanzamiento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("NombrePlataforma")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("NombrePlataforma")
                        .IsUnique();

                    b.ToTable("Plataformas");
                });

            modelBuilder.Entity("GameHub.Domain.Entities.Videojuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DesarrolladorId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateOnly>("FechaLanzamiento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<int>("GeneroId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DesarrolladorId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("Titulo")
                        .IsUnique();

                    b.ToTable("Videojuegos", t =>
                        {
                            t.HasCheckConstraint("CK_Videojuego_Precio", "\"Precio\" > 0");
                        });
                });

            modelBuilder.Entity("GameHub.Domain.Entities.VideojuegoPlataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<int>("PlataformaId")
                        .HasColumnType("integer");

                    b.Property<int>("VideojuegoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlataformaId");

                    b.HasIndex("VideojuegoId");

                    b.ToTable("VideojuegoPlataformas");
                });

            modelBuilder.Entity("GameHub.Domain.Entities.Videojuego", b =>
                {
                    b.HasOne("GameHub.Domain.Entities.Desarrollador", "Desarrollador")
                        .WithMany("Videojuegos")
                        .HasForeignKey("DesarrolladorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameHub.Domain.Entities.Genero", "Genero")
                        .WithMany("Videojuegos")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Desarrollador");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("GameHub.Domain.Entities.VideojuegoPlataforma", b =>
                {
                    b.HasOne("GameHub.Domain.Entities.Plataforma", "Plataforma")
                        .WithMany("VideojuegoPlataformas")
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameHub.Domain.Entities.Videojuego", "Videojuego")
                        .WithMany("VideojuegoPlataformas")
                        .HasForeignKey("VideojuegoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plataforma");

                    b.Navigation("Videojuego");
                });

            modelBuilder.Entity("GameHub.Domain.Entities.Desarrollador", b =>
                {
                    b.Navigation("Videojuegos");
                });

            modelBuilder.Entity("GameHub.Domain.Entities.Genero", b =>
                {
                    b.Navigation("Videojuegos");
                });

            modelBuilder.Entity("GameHub.Domain.Entities.Plataforma", b =>
                {
                    b.Navigation("VideojuegoPlataformas");
                });

            modelBuilder.Entity("GameHub.Domain.Entities.Videojuego", b =>
                {
                    b.Navigation("VideojuegoPlataformas");
                });
#pragma warning restore 612, 618
        }
    }
}
